name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: rumekk
          outputs: |
            dist/snake.svg
            dist/snake_dark.svg?palette=github-dark
      
      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Updated Snake animation"
          branch: main
          file_pattern: "dist/snake.svg dist/snake_dark.svg"
